import os
import sys

os.system('python run_gctw1_to_gctw5.py' + ' ' + sys.argv[1])
os.system('python run_gctw6_to_gctw10.py' + ' ' + sys.argv[1])
os.system('python run_gctw11_to_gctw15.py' + ' ' + sys.argv[1])
os.system('python run_gctw16_to_gctw20.py' + ' ' + sys.argv[1])
os.system('python run_gctw21_to_gctw25.py' + ' ' + sys.argv[1])
os.system('python run_gctw26_to_gctw30.py' + ' ' + sys.argv[1])

# if __name__=='__main__':
#     worker1 = Process(target=gctw01)
#     worker2 = Process(target=gctw02)
#     worker3 = Process(target=gctw03)
#     worker4 = Process(target=gctw04)
#     worker5 = Process(target=gctw05)
#     worker6 = Process(target=gctw06)
#     worker7 = Process(target=gctw07)
#     worker8 = Process(target=gctw08)
#     worker9 = Process(target=gctw09)
#     worker10 = Process(target=gctw10)
#     worker11 = Process(target=gctw11)
#     worker12 = Process(target=gctw12)
#     worker13 = Process(target=gctw13)
#     worker14 = Process(target=gctw14)
#     worker15 = Process(target=gctw15)
#     worker16 = Process(target=gctw16)
#     worker17 = Process(target=gctw17)
#     worker18 = Process(target=gctw18)
#     # worker19 = Process(target=gctw19)
#     worker20 = Process(target=gctw20)
#
#     worker1.start()
#     worker2.start()
#     worker3.start()
#     worker4.start()
#     worker5.start()
#     worker6.start()
#     worker7.start()
#     worker8.start()
#     worker9.start()
#     worker10.start()
#     worker11.start()
#     worker12.start()
#     worker13.start()
#     worker14.start()
#     worker15.start()
#     worker16.start()
#     worker17.start()
#     worker18.start()
#     # worker19.start()
#     worker20.start()